# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventSubscriber\NavigationSubscriber:
        arguments:
            $pagesRepository: '@App\Repository\PagesRepository'
            $requestStack: '@request_stack'
        tags:
            - { name: 'kernel.event_subscriber' }
   
    App\EventSubscriber\LegalInformationsEvents:
        arguments:
            $legalInformationsRepository: '@App\Repository\LegalInformationsRepository'
            $requestStack: '@request_stack'
        tags:
            - { name: 'kernel.event_subscriber' }

    App\EventSubscriber\MessageEvent:
        arguments:
            $messageContactsRepository: '@App\Repository\MessageContactsRepository'
            $requestStack: '@request_stack'
        tags:
            - { name: 'kernel.event_subscriber' }

    App\EventSubscriber\NewsletterEvent:
        arguments:
            $newsletterSuscribersRepository: '@App\Repository\NewsletterSuscribersRepository'
            $requestStack: '@request_stack'
            $formFactory: '@form.factory'
        tags:
            - { name: 'kernel.event_subscriber' }

    App\EventSubscriber\ProductsEvent:
        arguments:
            $productsRepository: '@App\Repository\ProductsRepository'
            $requestStack: '@request_stack'
        tags:
            - { name: 'kernel.event_subscriber' }

    App\EventSubscriber\ArticlesEvent:
        arguments:
            $articlesRepository: '@App\Repository\ArticlesRepository'
            $requestStack: '@request_stack'
        tags:
            - { name: 'kernel.event_subscriber' }